#importonce
// ---------------------------------------------------------------------------
// tables.asm - runtime tables generated by the assembler.
// Page-aligned block at RT_TABLES, small tables live in the runtime segment.
// ---------------------------------------------------------------------------

// Big tables: import with * = RT_TABLES
.macro RuntimeTables() {
    // bar buffers are filled every frame in IRQ TOP
    * = border_buf "bar buffers"
        .fill FLD_LINES, DEF_BORDER
    * = bg_buf
        .fill FLD_LINES, DEF_BG
    // $d011 per FLD line L = FLD_FIRST_LINE + i: YSCROLL (L + 2) & 7 never
    // matches L or L + 1, so no badline occurs. The last line restores
    // YSCROLL 3, which makes the next line a badline again.
    * = fld_tab "fld table"
        .fill FLD_LINES - 1, D011_BASE | ((FLD_FIRST_LINE + i + 2) & 7)
        .byte RT_D011
    * = bar_sin "bar sine"
        .fill SIN_LEN, round(BAR_POS_MAX / 2 + BAR_POS_MAX / 2 * sin(toRadians(i * 360 / SIN_LEN)))
    * = spr_xlo "sprite tables"
        .fill SIN_LEN, <sprX(i)
    * = spr_xhi
        .fill SIN_LEN, >sprX(i)
    * = spr_y
        .fill SIN_LEN, round((SPR_Y_MIN + SPR_Y_MAX) / 2 + (SPR_Y_MAX - SPR_Y_MIN) / 2 * cos(toRadians(i * 360 / SIN_LEN)))
}

.function sprX(i) {
    .return round((SPR_X_MIN + SPR_X_MAX) / 2 + (SPR_X_MAX - SPR_X_MIN) / 2 * sin(toRadians(i * 360 / SIN_LEN)))
}

// Small tables: emitted inside the runtime code segment
.macro RuntimeSmallTables() {
// 8 presets x 15 colours, symmetric gradients
rt_presets:
        .byte 6, 6,14,14, 3, 3, 1, 1, 1, 3, 3,14,14, 6, 6   // blue
        .byte 2, 2, 8, 8,10,10, 7, 1, 7,10,10, 8, 8, 2, 2   // fire
        .byte 11,11,5, 5,13,13, 1, 1, 1,13,13, 5, 5,11,11   // green
        .byte 11,11,12,12,15,15,1, 1, 1,15,15,12,12,11,11   // grey
        .byte 6, 6, 4, 4,10,10, 1, 1, 1,10,10, 4, 4, 6, 6   // purple
        .byte 9, 9, 8, 8, 7, 7, 1, 1, 1, 7, 7, 8, 8, 9, 9   // gold
        .byte 6, 6, 3, 3,13,13, 1, 1, 1,13,13, 3, 3, 6, 6   // cyan
        .byte 2, 8, 7, 5, 3,14, 6, 1, 6,14, 3, 5, 7, 8, 2   // rainbow
rt_preset_offs:
        .fill PRESET_COUNT, i * BAR_HEIGHT
rt_bar_phase_offs:
        .fill BAR_COUNT, i * BAR_PHASE_STEP
rt_bar_fixed:
        .byte BAR_FIXED_0, BAR_FIXED_1, BAR_FIXED_2
rt_cyc_tab:
        .byte 9, 2, 8,10,15, 7, 1, 1, 1, 7,15,10, 8, 2, 9, 9
rt_spr_colors:
        .byte 1, 7, 3, 5,13,14,10,15
}

// 21x21 ball, generated
.macro SpriteBall() {
    .for (var y = 0; y < 21; y++) {
        .for (var b = 0; b < 3; b++) {
            .var v = 0
            .for (var bit = 0; bit < 8; bit++) {
                .var x = b * 8 + bit
                .var dx = x - 10
                .var dy = y - 10
                .if (x < 21 && dx * dx + dy * dy <= 110) .eval v = v | ($80 >> bit)
            }
            .byte v
        }
    }
    .byte 0
}
